easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            form:
                fields:
                - { property: 'title' }
                - { property: 'slug' }
                - { property: 'status' }
                - { property: 'description' }
                - { property: 'createdAt' }
                - { property: 'updatedat' }
                - { property: 'deletedat' }
                - { property: 'imageFile', type: 'file'}
                - { property: 'ksp1'}
                - { property: 'ksp2'}
                - { property: 'ksp3'}
                - { property: 'titlek1'}
                - { property: 'titlek2'}
                - { property: 'titlek3'}
        
        Champions:
            class: App\Entity\Champions
            form:
                fields:
                - { property: 'title' }
                - { property: 'slug' }
                - { property: 'status' }
                - { property: 'description' }
                - { property: 'createdAt' }
                - { property: 'updatedat' }
                - { property: 'deletedat' }
                - { property: 'imageFile', type: 'file'}
        
        Clubs:
            class: App\Entity\Clubs 
        
        Competitions:
            class: App\Entity\Competitions
            form:
                fields:
                - { property: 'title' }
                - { property: 'slug' }
                - { property: 'status' }
                - { property: 'description' }
                - { property: 'createdAt' }
                - { property: 'updatedat' }
                - { property: 'deletedat' }
                - { property: 'date' }
                - { property: 'imageFile', type: 'file'}
                - { property: 'intro'}
        
        Articles: 
            class: App\Entity\Articles
            form:
                fields:
                - { property: 'fkCategory', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Category'} }
                - { property: 'title' }
                - { property: 'slug' }
                - { property: 'status' }
                - { property: 'description' }
                - { property: 'createdAt' }
                - { property: 'updatedat' }
                - { property: 'deletedat' }
                - { property: 'imageFile', type: 'file'}
                - { property: 'author'}
        #pensez à duppliquer la ligne pour le bo avec entity correspondante 

    