easy_admin:
    entities:
        Category:
            class: App\Entity\Category
        
        Champions:
            class: App\Entity\Champions 
        
        Clubs:
            class: App\Entity\Clubs 
        
        Competitions:
            class: App\Entity\Competitions 
        
        Articles: 
            class: App\Entity\Articles
            form:
                fields:
                - { property: 'fkCategory', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Category'} }
                - { property: 'title' }
                - { property: 'slug' }
                - { property: 'status' }
                - { property: 'description' }
                - { property: 'createdAt' }
                - { property: 'updatedat' }
                - { property: 'deletedat' }
                - { property: 'imageFile', type: 'file'}
                - { property: 'author'}
        #pensez à duppliquer la ligne pour le bo avec entity correspondante 

    