parameters :
    app.path.articles : /img/articles

vich_uploader:
    db_driver: orm

    mappings:
        articles:
            uri_prefix: '%app.path.articles%'
            upload_destination: '%kernel.project_dir%/public/img/articles'
