parameters :
    app.path.articles : /img/articles
    app.path.competitions : /img/competitions
    app.path.champions : /img/champions
    app.path.category : /img/category

vich_uploader:
    db_driver: orm

    mappings:
        articles:
            uri_prefix: '%app.path.articles%'
            upload_destination: '%kernel.project_dir%/public/img/articles'
    
        competitions:
            uri_prefix: '%app.path.competitions%'
            upload_destination: '%kernel.project_dir%/public/img/competitions'

        champions:
            uri_prefix: '%app.path.champions%'
            upload_destination: '%kernel.project_dir%/public/img/champions'

        category:
            uri_prefix: '%app.path.category%'
            upload_destination: '%kernel.project_dir%/public/img/category'
